### ISSUE TITLE
Show leaders and group description on the research group pillars (home page)

### ISSUE THREAD

**Issue by GezimSejdiu** [SmartDataAnalytics/sda.tech#12]
Add possibility to:

- [x] display group leaders already defined on sda.tech.ttl (e.g [this one](https://github.com/SmartDataAnalytics/sda.tech/blob/develop/rdf-data/sda.tech.ttl#L1487))
- [x] show group description besides group icon and name
- [x] add link [Read More]() to redirect to a specific group page 

on the section **Specialized Groups Working under SDA** on home page.

**Comment by RohanAsmat** [comment]
Instead of adding the Read More Link, specific group pages are linked with icon and name of the groups as increasing the Card Size makes the complete description fit in the screen space, plus it looks more cleaner and serves the purpose. Showing uncontrolled half abstracts about group wasn't looking good.
![screenshot from 2018-03-05 14-40-06](https://user-images.githubusercontent.com/7516846/36977949-338c94f0-2083-11e8-92f0-84ebbbfd37ec.png)

**Comment by RohanAsmat** [comment]
Appropriate leaders linked.
