### ISSUE TITLE
Design--Tweets and Blog Posts on the main page

### ISSUE THREAD

**Issue by S6savahd** [SmartDataAnalytics/sda.tech#35]
This is a design decision, I just report what my eyes catch. Having so many tweets below the main information on the main page makes it longer than needed. The blog posts are supposed to be seen/shown side by side of the tweets, however currently it shows only one. 
Suggestions:  In general, I think showing tweets on the side of the other pages starting from the top would make the pages more informative. Maybe even skip the main page, in any other page (or all of them) tweets on the right and short view of blog posts on the left.

**Comment by AdrianBajraktari** [comment]
I totally agree with the height of the Twitter Box (and therefore the whole "Keep Connected with Our Posts" Section). It really does not need to be that long, especially since there is only one blog post currently.
To the other suggestion: I personally think it would be a bit redundant to have blog posts and tweets on every page.  It may also harm the all in all slim design of the site. Maybe others could share their opinion on this one?

**Comment by RohanAsmat** [comment]
I agree with @AdrianBajraktari, It would be information overload as mostly people would be accesig blogs our tweets from social media shares like twitter and facebook ! And for every page if we keep their focus on the intended task, it is much better!

**Comment by GezimSejdiu** [comment]
Hi @AdrianBajraktari and @RohanAsmat , what @S6savahd was referring is this one: http://sda.cs.uni-bonn.de/projects/ (you see on the right side we repeat the partners, and supported by and twitter ). So if you can make the layout to look the same would be great I guess.

The user, does not necessarily need to go back to the main page to see them, right?

**Comment by AdrianBajraktari** [comment]
@GezimSejdiu I personally think for the Tweets it is a bit unnecessary, since there is a limited amount of Tweets shown anyway. If someone wanted to look at the tweets, they need to head over to Twitter to see more than five tweets.
It is just a personal opinion, but I think it would just blow up the layout (sidebars don't work out on mobile anyway) and having to raise the mouse cursor to the main menu and click on "about" or the logo is not really a long way to go. But if there is a real flavor for having blog and tweets on each page, I will of course change the layout accordingly ;)

**Comment by GezimSejdiu** [comment]
> @GezimSejdiu I personally think for the Tweets it is a bit unnecessary since there is a limited amount of Tweets shown anyway. If someone wanted to look at the tweets, they need to head over to Twitter to see more than five tweets.

reg. this I think we have to remove the limit on the tweets (not only showing 5 top tweets -- on the old page you can scroll over the tweets and see all of them.)
and reg. blogs -- no there is no request for showing them on every page -- just we need to add the menu on the header which lists all the blog post (e.g. http://sda.cs.uni-bonn.de/blog/) besides having it only on the `+` sign. 

But if you and Rohan consider it unnecessary, we could then discuss it with others as well and make a decision on why we want to have it there.

Best,
